packages:
  - apps/*
  - packages/*
catalog:
  "@ai-sdk/react": ^2.0.15
  "@blocknote/core": "^0.33.0"
  "@blocknote/mantine": "^0.33.0"
  "@blocknote/react": "^0.33.0"
  "@blocknote/server-util": "^0.33.0"
  "@dnd-kit/core": ^6.1.0
  "@dnd-kit/sortable": ^8.0.0
  "@dnd-kit/utilities": ^3.2.2
  "@emoji-mart/data": ^1.2.1
  "@emoji-mart/react": ^1.1.1
  "@headlessui/react": ^1.7.18
  "@hookform/resolvers": ^3.3.4
  "@infra-blocks/zod-utils": ^0.4.5
  "@mapbox/geo-viewport": ^0.5.0
  "@neondatabase/serverless": ^0.9.0
  "@next/eslint-plugin-next": ^15
  "@oslojs/crypto": ^1.0.1
  "@oslojs/encoding": ^1.1.0
  "@radix-ui/react-accordion": ^1.1.2
  "@radix-ui/react-alert-dialog": ^1.1.2
  "@radix-ui/react-avatar": ^1.1.1
  "@radix-ui/react-checkbox": ^1.1.2
  "@radix-ui/react-collapsible": ^1.1.1
  "@radix-ui/react-context-menu": ^2.2.1
  "@radix-ui/react-dialog": ^1.1.1
  "@radix-ui/react-dismissable-layer": ^1.1.5
  "@radix-ui/react-dropdown-menu": ^2.1.15
  "@radix-ui/react-focus-scope": ^1.1.2
  "@radix-ui/react-label": ^2.0.2
  "@radix-ui/react-popover": ^1.1.6
  "@radix-ui/react-portal": ^1.1.2
  "@radix-ui/react-scroll-area": ^1.1.0
  "@radix-ui/react-select": ^2.1.4
  "@radix-ui/react-separator": ^1.1.0
  "@radix-ui/react-slider": ^1.2.1
  "@radix-ui/react-slot": ^1.0.2
  "@radix-ui/react-tabs": "^1.1.2"
  "@radix-ui/react-switch": ^1.0.3
  "@radix-ui/react-toast": ^1.2.2
  "@radix-ui/react-tooltip": ^1.1.2
  "@react-email/components": 0.0.28
  "@t3-oss/env-nextjs": ^0.11.1
  "@tailwindcss/container-queries": ^0.1.1
  "@tailwindcss/forms": ^0.5.7
  "@tailwindcss/typography": ^0.5.10
  "@tanstack/react-query": ^5.29.0
  "@tanstack/react-query-devtools": ^5.29.0
  "@tanstack/react-table": ^8.21.3
  "@tanstack/react-virtual": ^3.10.8
  "@types/bcryptjs": ^2.4.6
  "@types/eslint": ^8.56.5
  "@types/geojson": ^7946.0.16
  "@types/lodash-es": ^4.17.12
  "@types/mapbox__geo-viewport": ^0.5.3
  "@types/node": "^20.11.24"
  "@types/papaparse": ^5.3.14
  "@types/pg": ^8.11.10
  "@types/react": "^19.0.1"
  "@types/react-dom": "^19.0.2"
  "@types/supercluster": ^7.1.3
  "@types/unique-slug": ^4.0.0
  "@types/uuid": ^9.0.8
  "@types/ws": ^8.5.10
  "@typescript-eslint/eslint-plugin": ^8.15.0
  "@typescript-eslint/parser": ^8.15.0
  "@vercel/analytics": ^1.4.1
  "@vercel/blob": ^0.23.3
  "@vercel/style-guide": "^6.0.0"
  "@vercel/speed-insights": ^1.1.0
  ai: ^5.0.56
  autoprefixer: ^10.0.1
  bcryptjs: ^2.4.3
  bufferutil: ^4.0.8
  class-variance-authority: ^0.7.0
  clsx: ^2.1.0
  cmdk: ^1.0.4
  cobe: ^0.6.3
  compressorjs: ^1.2.1
  date-fns: ^3.6.0
  dotenv: ^16.4.5
  drizzle-kit: ^0.28.0
  drizzle-orm: ^0.38.0
  drizzle-zod: ^0.7.1
  embla-carousel-react: ^8.5.1
  emoji-mart: ^5.6.0
  emoji-regex: ^10.4.0
  eslint: ^9.15.0
  eslint-config-next: 15.0.3
  eslint-config-prettier: ^9.1.0
  eslint-plugin-turbo: ^2.3.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.2
  eslint-plugin-react-hooks: ^5.0.0
  geojson: ^0.5.0
  globals: ^15.12.0
  jose: ^5.9.6
  lodash-es: ^4.17.21
  lucide-react: ^0.501.0
  lucide-static: ^0.454.0
  motion: 12.0.0-alpha.2
  next: 15.5.3
  next-safe-action: ^7.10.4
  next-themes: ^0.3.0
  papaparse: ^5.4.1
  pg: ^8.13.0
  postcss: ^8.4.49
  prettier: ^3.2.5
  prettier-plugin-tailwindcss: ^0.6.8
  react-day-picker: ^9.2.1
  react: 19.0.0
  react-dom: 19.0.0
  react-email: 3.0.2
  react-hook-form: ^7.51.3
  react-resizable-panels: ^2.1.4
  resend: 6.0.1
  slugify: ^1.6.6
  sonner: ^1.4.41
  stripe: "^17.5.0"
  supercluster: ^8.0.1
  tailwindcss: ^3.4.17
  tailwind-merge: ^2.2.1
  tailwindcss-animate: ^1.0.7
  ts-node: ^10.9.2
  turbo: ^2.3.0
  typescript: ^5.8.3
  typescript-eslint: ^8.15.0
  unique-slug: ^4.0.0
  use-supercluster: ^1.2.0
  uuid: ^9.0.1
  vaul: ^1.1.2
  vitest: ^2.1.1
  ws: ^8.18.0
  zod: 3.25.1
  zod-form-data: ^2.0.2
