import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mapform/ui/globals.css";
import { cn } from "@mapform/lib/classnames";
import { RootProviders } from "~/components/root-providers";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className={cn("h-full", inter.className)}>
        <RootProviders>{children}</RootProviders>
      </body>
    </html>
  );
}
